name: Test Compilation CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      
    - name: Install dependencies
      run: |
            sudo apt install libcurl4-gnutls-dev
            sudo apt install libwebsockets-dev
      
    - name: Build main
      run: make main
